Repository M4-Cross-Poll/frontend, pull requests merged in 2020-04, with the labels that each got.

#9 Activity form setup
  .github/PULL_REQUEST_TEMPLATE.md
  App.js
  components/ActivityPicker.js
  components/DatePicker.js
  package-lock.json
  package.json
  screens/NewActivityForm.js
Labels: feature

#10 Create hardcoded mock data to use while building out the frontend
  mockData/mockData.js
Labels: chore, frontend

#11 Navigation setup
  App.js
  components/ActivityPicker.js
  components/DatePicker.js
  components/UserWelcome.js
  components/WeatherWindow.js
  screens/HomeScreen.js
  screens/LoginScreen.js
  screens/NewActivityForm.js
Labels: enhancement, feature, frontend

#12 Displaying mock data on page
  components/ActivityCard.js
  components/UserLandingPage.js
  mockData/mockData.js
  screens/HomeScreen.js
Labels: chore, enhancement, frontend

#13 Testing setup
  .travis.yml
  App.js
  components/ActivityCard/ActivityCard.js
  components/ActivityCard/ActivityCard.test.js
  components/ActivityPicker/ActivityPicker.js
  components/ActivityPicker/ActivityPicker.test.js
  components/DatePicker/DatePicker.js
  components/DatePicker/DatePicker.test.js
  components/UserLandingPage/UserLandingPage.js
  components/UserLandingPage/UserLandingPage.test.js
  components/UserWelcome/UserWelcome.js
  components/UserWelcome/UserWelcome.test.js
  components/WeatherWindow/WeatherWindow.js
  components/WeatherWindow/WeatherWindow.test.js
  package-lock.json
  package.json
  screens/HomeScreen/HomeScreen.js
  screens/HomeScreen/HomeScreen.test.js
  screens/LoginScreen/LoginScreen.js
  screens/LoginScreen/LoginScreen.test.js
  screens/NewActivityForm.js
  screens/NewActivityForm/NewActivityForm.js
  screens/NewActivityForm/NewActivityForm.test.js
Labels: chore, frontend

#14 Activity form refactor
  App.js
  components/ActivityPicker/ActivityPicker.js
  components/ActivityPicker/ActivityPicker.test.js
  components/DatePicker/DatePicker.js
  components/DatePicker/DatePicker.test.js
  package-lock.json
  package.json
  screens/HomeScreen/HomeScreen.js
  screens/NewActivityForm/NewActivityForm.js
  screens/UserActivityScreen/UserActivityScreen.js
Labels: frontend

#15 Styling user activity cards
  components/ActivityCard/ActivityCard.js
  components/UserLandingPage/UserLandingPage.js
  mockData/mockData.js
Labels: chore, enhancement, frontend, phase 3

#16 Global state setup
  App.js
  components/UserLandingPage/UserLandingPage.js
  context/ActivityContext.js
  provider/ActivityProvider.js
  screens/HomeScreen/HomeScreen.js
Labels: feature, frontend

#17 Activity api integration
  App.js
  apiCalls/apiCalls.js
  apiCalls/apiCalls.test.js
  components/UserLandingPage/UserLandingPage.js
  package-lock.json
  package.json
  screens/HomeScreen/HomeScreen.js
  screens/NewActivityForm/NewActivityForm.js
Labels: feature, frontend

#18 Displaying activity details
  App.js
  components/ActivityCard/ActivityCard.js
  components/UserLandingPage/UserLandingPage.js
  provider/ActivityProvider.js
  screens/ActivityDetails/ActivityDetails.js
Labels: chore, enhancement, frontend

#19 Api testing
  apiCalls/apiCalls.js
  apiCalls/apiCalls.test.js
  components/ActivityCard/ActivityCard.test.js
  components/UserLandingPage/UserLandingPage.test.js
  components/UserWelcome/UserWelcome.test.js
  components/WeatherWindow/WeatherWindow.test.js
  screens/HomeScreen/HomeScreen.test.js
  screens/LoginScreen/LoginScreen.test.js
  screens/NewActivityForm/NewActivityForm.test.js
  screens/UserActivityScreen/UserActivityScreen.js
  yarn.lock
Labels: chore, frontend

#21 General style refactor
  App.js
  apiCalls/apiCalls.js
  apiCalls/apiCalls.test.js
  assets/RainorShineLogo.png
  assets/RainorShineTitle.png
  components/ActivityCard/ActivityCard.js
  components/ActivityCard/__snapshots__/ActivityCard.test.js.snap
  components/Loading/Loading.js
  components/Loading/Loading.test.js
  components/Loading/__snapshots__/Loading.test.js.snap
  components/UserLandingPage/UserLandingPage.js
  components/UserLandingPage/__snapshots__/UserLandingPage.test.js.snap
  components/UserWelcome/UserWelcome.js
  components/UserWelcome/UserWelcome.test.js
  components/UserWelcome/__snapshots__/UserWelcome.test.js.snap
  components/WeatherWindow/WeatherWindow.js
  components/WeatherWindow/WeatherWindow.test.js
  components/WeatherWindow/__snapshots__/WeatherWindow.test.js.snap
  screens/HomeScreen/HomeScreen.js
  screens/LoginScreen/LoginScreen.js
  screens/LoginScreen/__snapshots__/LoginScreen.test.js.snap
Labels: enhancement, frontend

#22 Reformat conditionals
  components/UserWelcome/__snapshots__/UserWelcome.test.js.snap
  screens/ActivityDetails/ActivityDetails.js
Labels: chore, enhancement, feature, frontend, phase 3

#23 Displaying activity details
  apiCalls/apiCalls.js
  apiCalls/apiCalls.test.js
  components/ActivityCard/ActivityCard.js
  components/UserLandingPage/UserLandingPage.js
  components/UserLandingPage/UserLandingPage.test.js
  components/UserWelcome/UserWelcome.js
  components/WeatherWindow/WeatherWindow.js
  components/WeatherWindow/WeatherWindow.test.js
  components/WeatherWindow/__snapshots__/WeatherWindow.test.js.snap
  screens/ActivityDetails/ActivityDetails.js
  screens/HomeScreen/HomeScreen.js
Labels: feature, frontend

#24 New activity posting
  App.js
  apiCalls/apiCalls.js
  apiCalls/apiCalls.test.js
  screens/ActivityDetails/ActivityDetails.js
  screens/ActivityDetails/ActivityDetails.test.js
  screens/ActivityDetails/__snapshots__/ActivityDetails.test.js.snap
  screens/HomeScreen/HomeScreen.test.js
  screens/HomeScreen/__snapshots__/HomeScreen.test.js.snap
  screens/NewActivityForm/NewActivityForm.js
  screens/NewActivityForm/NewActivityForm.test.js
  screens/NewActivityForm/__snapshots__/NewActivityForm.test.js.snap
  screens/UserActivityScreen/UserActivityScreen.test.js
Labels: feature, frontend

#25 Delete request functionality
  apiCalls/apiCalls.js
  components/ActivityCard/ActivityCard.js
  components/ActivityCard/__snapshots__/ActivityCard.test.js.snap
  components/UserLandingPage/UserLandingPage.js
  components/UserLandingPage/__snapshots__/UserLandingPage.test.js.snap
  screens/HomeScreen/HomeScreen.js
Labels: enhancement, feature, frontend

#27 Weather icon refactor
  assets/clear-day.png
  assets/clear-night.png
  assets/cloudy.png
  assets/fog.png
  assets/partly-cloudy-day.png
  assets/partly-cloudy-night.png
  assets/rain.png
  assets/sleet.png
  assets/snow.png
  assets/wind.png
  components/WeatherWindow/WeatherWindow.js
  components/WeatherWindow/__snapshots__/WeatherWindow.test.js.snap
  screens/LoginScreen/LoginScreen.js
Labels: feature, frontend

#31 Sort activities
  components/UserLandingPage/UserLandingPage.js
  components/UserLandingPage/UserLandingPage.test.js
  components/UserLandingPage/__snapshots__/UserLandingPage.test.js.snap
  components/WeatherWindow/WeatherWindow.js
  screens/HomeScreen/HomeScreen.js
Labels: enhancement, feature, frontend

#32 Add conditional rendering for filter button
  screens/HomeScreen/HomeScreen.js
Labels: enhancement, feature, frontend

#33 Minor bug fixes
  components/ActivityCard/ActivityCard.js
  components/ActivityCard/__snapshots__/ActivityCard.test.js.snap
  components/UserLandingPage/__snapshots__/UserLandingPage.test.js.snap
  components/UserWelcome/__snapshots__/UserWelcome.test.js.snap
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/apiCalls/apiCalls.js.html
  coverage/lcov-report/apiCalls/index.html
  coverage/lcov-report/assets/RainorShineLogo.png.html
  coverage/lcov-report/assets/RainorShineTitle.png.html
  coverage/lcov-report/assets/clear-day.png.html
  coverage/lcov-report/assets/clear-night.png.html
  coverage/lcov-report/assets/cloudy.png.html
  coverage/lcov-report/assets/fog.png.html
  coverage/lcov-report/assets/index.html
  coverage/lcov-report/assets/partly-cloudy-day.png.html
  coverage/lcov-report/assets/partly-cloudy-night.png.html
  coverage/lcov-report/assets/rain.png.html
  coverage/lcov-report/assets/sleet.png.html
  coverage/lcov-report/assets/snow.png.html
  coverage/lcov-report/assets/wind.png.html
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/components/ActivityCard/ActivityCard.js.html
  coverage/lcov-report/components/ActivityCard/index.html
  coverage/lcov-report/components/Loading/Loading.js.html
  coverage/lcov-report/components/Loading/index.html
  coverage/lcov-report/components/UserLandingPage/UserLandingPage.js.html
  coverage/lcov-report/components/UserLandingPage/index.html
  coverage/lcov-report/components/UserWelcome/UserWelcome.js.html
  coverage/lcov-report/components/UserWelcome/index.html
  coverage/lcov-report/components/WeatherWindow/WeatherWindow.js.html
  coverage/lcov-report/components/WeatherWindow/index.html
  coverage/lcov-report/context/ActivityContext.js.html
  coverage/lcov-report/context/index.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/screens/ActivityDetails/ActivityDetails.js.html
  coverage/lcov-report/screens/ActivityDetails/index.html
  coverage/lcov-report/screens/HomeScreen/HomeScreen.js.html
  coverage/lcov-report/screens/HomeScreen/index.html
  coverage/lcov-report/screens/LoginScreen/LoginScreen.js.html
  coverage/lcov-report/screens/LoginScreen/index.html
  coverage/lcov-report/screens/NewActivityForm/NewActivityForm.js.html
  coverage/lcov-report/screens/NewActivityForm/index.html
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  screens/ActivityDetails/ActivityDetails.js
Labels: frontend

#34 Style bugs
  App.js
  components/ActivityCard/ActivityCard.js
  components/ActivityCard/__snapshots__/ActivityCard.test.js.snap
  components/UserLandingPage/UserLandingPage.js
  components/UserLandingPage/__snapshots__/UserLandingPage.test.js.snap
  context/ActivityContext.js
  provider/ActivityProvider.js
  screens/ActivityDetails/ActivityDetails.js
  screens/HomeScreen/HomeScreen.js
  screens/LoginScreen/LoginScreen.js
  screens/LoginScreen/__snapshots__/LoginScreen.test.js.snap
  screens/NewActivityForm/NewActivityForm.js
  screens/NewActivityForm/__snapshots__/NewActivityForm.test.js.snap
Labels: frontend
